### ISSUE TITLE
Wrong type declaration

### ISSUE THREAD

**Issue by Nilabhra** [petuum/pirlib#17]
The `generate` and `execute` method in the `backend` parent class uses have an argument called `graph` of type `pirlib.pir.Graph` but they are not used by the child classes.
https://github.com/petuum/pirlib/blob/c53bd8d7512cbbd2c5aa186b808ee73d0de654db/pirlib/backends/backend.py#L17
https://github.com/petuum/pirlib/blob/c53bd8d7512cbbd2c5aa186b808ee73d0de654db/pirlib/backends/backend.py#L25

Instead an argument called `package` of type `pirlib.pir.Package` is introduced and used.
https://github.com/petuum/pirlib/blob/c53bd8d7512cbbd2c5aa186b808ee73d0de654db/pirlib/backends/docker_batch.py#L33

Although this isn't really a bug, I decided to report it as an inconsistency.

**Comment by zhanyuanucb** [comment]
Good catch!
It should be `Package` in the `backend`.

**Comment by Nilabhra** [comment]
@zhanyuanucb Let me know if you want me to submit a separate PR for this.

**Comment by zhanyuanucb** [comment]
Yes. Please go ahead and do that.
Thanks!
