### ISSUE TITLE
Add Argo Workflow backend

### ISSUE THREAD

**Issue by zhanyuanucb** [petuum/pirlib#18]
Currently, PIRlib can execute pipelines locally, either via direct execution or via containerized execution using `docker-compose`. In order to support distributed execution of pipelines, where data is shared between containers via NFS, a framework like Argo Workflows can be leveraged.

Initially replicating a multi-step pipeline such as the one used in the docker example would be a good first step towards complete integration.

**Comment by Nilabhra** [comment]
@zhanyuanucb Closing this as the PR is merged.
