### ISSUE TITLE
Support for specifying input files in the Argo backend

### ISSUE THREAD

**Issue by Nilabhra** [petuum/pirlib#22]
Currently, only NFS directories can be specified as inputs to the Argo Workflows. The `inproc` and the `docker` backend both have the support for files (stored in an NFS) to be specified as input.

The Argo backend can be updated to have support for input files along with directories.

**Comment by zhanyuanucb** [comment]
Could you briefly explain what to change to add this support?

**Comment by Nilabhra** [comment]
@zhanyuanucb 
>Could you briefly explain what to change to add this support?

The Argo backend needs to be modified to add a `subPath` for inputs and outputs which are files.
